"use client";

import { MarketingInfoPage } from "@/features/home/MarketingInfoPage";
import type { PublicPageData } from "@/features/home/marketingPages";
import { BadgeCheck } from "lucide-react";

export default function TermsOfServicePage() {
  const page: PublicPageData = {
    eyebrow: "Legal",
    title: "Terms of Service",
    description: "Rules for account behavior, subscriptions, safety reports, moderation, content, protected dashboards, and platform access.",
    icon: BadgeCheck,
    cta: { label: "Create Account", href: "/register" },
    highlights: ["Users must provide accurate profile details.", "Premium unlocks paid features and billing actions.", "Unsafe behavior can lead to enforcement."],
    metrics: [{ value: "18+", label: "intended users" }, { value: "Clear", label: "rules" }, { value: "Fair", label: "review process" }],
    sections: [
      { title: "Account rules", body: "Members should use truthful profiles, secure login details, respectful communication, and one account per person.", points: ["No impersonation.", "No scams.", "No harassment."] },
      { title: "Subscriptions", body: "Premium features, plan changes, invoices, refunds, and payment questions connect to finance and support workflows.", points: ["Plan terms.", "Refund review.", "Billing support."] },
      { title: "Enforcement", body: "Reports can lead to warnings, restrictions, suspension, removal, or escalation depending on severity.", points: ["Support review.", "Admin action.", "Super-admin oversight."] },
    ],
    longForm: [
      { title: "Eligibility and agreement", paragraphs: ["You must be at least 18 years old, legally capable of entering an agreement, and not prohibited from using the service under applicable law. By registering, accessing, or using ConnectLove, you agree to these Terms and acknowledge the Privacy Policy and other incorporated policies.", "You may not use the service if your account was previously terminated for serious violations unless ConnectLove gives written permission. We may request age, identity, eligibility, or account-security verification."], points: ["Adults aged 18 or older only.", "One genuine personal account per person unless permitted.", "Accurate registration information.", "No access following an unapproved termination."] },
      { title: "Account security and profile responsibilities", paragraphs: ["You are responsible for safeguarding your credentials and activity through your account. Notify us promptly if you suspect unauthorized use. Do not sell, rent, transfer, share, or provide access to an account.", "Profile information and photos must be yours or used with permission, reasonably current, and not materially deceptive. Verification is a trust signal and not a guarantee of identity, conduct, compatibility, criminal history, or safety."], points: ["Never share passwords or OTPs.", "No impersonation or deceptive profiles.", "No unauthorized images.", "Update material profile changes."] },
      { title: "Acceptable use and prohibited conduct", paragraphs: ["Use ConnectLove for lawful adult social and dating purposes. Respect consent, boundaries, intellectual property, privacy, and the safety of other people.", "You must not harass, threaten, stalk, discriminate unlawfully, exploit, blackmail, defraud, solicit money, promote investments, distribute malware, scrape data, automate engagement, create fake accounts, evade restrictions, publish private information, send non-consensual sexual material, facilitate trafficking, or use the service for illegal commercial activity."], points: ["No scams or financial solicitation.", "No hate, threats, or harassment.", "No scraping, bots, or reverse engineering beyond lawful rights.", "No sexual exploitation or content involving minors."] },
      { title: "Member content and limited licence", paragraphs: ["You retain ownership of content you lawfully create. By uploading content, you grant ConnectLove a non-exclusive, worldwide, royalty-free licence to host, store, reproduce, format, display, and transmit it only as reasonably needed to operate, secure, improve, and promote the service in accordance with your settings and applicable law.", "You represent that you have necessary rights and that content does not violate law or another person’s privacy, publicity, copyright, trademark, or other rights. You can remove profile content, subject to retention needed for reports, backups, disputes, safety, and law."], points: ["Only upload content you may lawfully use.", "Profile visibility follows product settings.", "Public story use requires separate consent.", "Reports may preserve relevant content."] },
      { title: "Subscriptions, payments, and cancellation", paragraphs: ["Paid plans provide the features described at checkout for the stated period, subject to eligibility, safety controls, technical availability, and fair use. Prices, taxes, renewal, and cancellation terms should be displayed before purchase. Premium does not guarantee views, likes, matches, dates, or relationships.", "You authorize the payment provider to charge the displayed amount. Cancellation ordinarily stops future renewal where applicable; it does not automatically refund a completed period. Refunds are assessed under the purchase terms, payment-channel rules, applicable consumer law, and transaction facts."], points: ["Review price and renewal before payment.", "Keep payment credentials out of support messages.", "No chargeback or refund abuse.", "Core safety tools are not paid features."] },
      { title: "Moderation, suspension, and termination", paragraphs: ["We may investigate reports and use proportionate measures including content removal, warning, visibility limits, feature restrictions, verification requirements, suspension, or account termination. Serious safety, fraud, legal, or security concerns may justify immediate temporary action while a review continues.", "We may consider available account, message, payment, verification, device, and report context. We do not promise to disclose confidential evidence, reporter identity, detection methods, or every enforcement detail. Knowingly false or abusive reports also violate these Terms."], points: ["Protect members during credible risk.", "Preserve relevant evidence where lawful.", "Allow review or grievance paths where applicable.", "Termination can end access to paid features."] },
      { title: "Service availability and third parties", paragraphs: ["ConnectLove may change, test, suspend, or discontinue features. We aim for reliable service but do not guarantee uninterrupted, error-free, or universally available access. Device, network, location, account, and provider limitations can affect functionality.", "Payment, verification, communication, hosting, map, or other third-party services may have their own terms. ConnectLove is not responsible for independent off-platform conduct between members, though platform-related concerns can be reported."], points: ["Features may evolve.", "Back up information you need where permitted.", "Review third-party terms when shown.", "Use caution in off-platform interactions."] },
      { title: "Disclaimers and limitation of responsibility", paragraphs: ["To the maximum extent permitted by law, the service is provided on an “as available” basis. We do not warrant compatibility, identity, background, intentions, conduct, relationship outcomes, or that every harmful user will be detected.", "Nothing in these Terms excludes liability or consumer rights that cannot legally be excluded. Any limitation of liability must be interpreted under applicable law and in light of the specific loss, conduct, and jurisdiction. You remain responsible for interactions, meetings, and decisions involving other members."], points: ["No guarantee of romantic outcomes.", "Verification is not a safety warranty.", "Use safe meeting practices.", "Non-waivable legal rights remain protected."] },
      { title: "Changes, governing rules, and contact", paragraphs: ["We may update these Terms for product, security, operational, or legal reasons. Material changes will be communicated as required, and fresh agreement will be requested where necessary. The effective version presented by the service governs future use.", "Questions, billing disputes, content complaints, or account grievances can be submitted through Contact Us. Governing law, forum, mandatory consumer remedies, and dispute procedures apply according to the operator’s legally published business details and applicable law; these Terms do not remove rights that cannot be waived."], points: ["Review update notices.", "Stop using the service if you do not accept future terms.", "Contact support before escalating where appropriate.", "Mandatory legal remedies remain available."] },
    ],
    actions: [{ title: "Accept", body: "User agrees by creating or using an account." }, { title: "Use responsibly", body: "User follows platform and safety rules." }, { title: "Resolve issue", body: "Support/admin handles disputes, reports, and billing questions." }],
    roleAccess: [{ role: "User", access: "Must follow account, content, safety, and subscription rules." }, { role: "Support/Admin", access: "May review tickets, reports, users, and enforcement context." }, { role: "Super Admin", access: "May manage roles, settings, security, logs, and final escalations." }],
    faq: [{ question: "Can accounts be restricted?", answer: "Yes. Abuse, scams, impersonation, harassment, fraud, security threats, or safety risk can lead to restrictions or termination." }, { question: "Are subscriptions covered?", answer: "Yes. Paid feature use, billing, cancellation, renewal, and refund review are covered." }, { question: "Does a match mean consent?", answer: "No. Consent remains voluntary, specific, and revocable at every stage." }, { question: "Does verification guarantee identity or safety?", answer: "No. It is one trust signal and does not replace personal judgment or safe meeting practices." }],
  };
  return <MarketingInfoPage page={page} />;
}
