"use client";

import { MarketingInfoPage } from "@/features/home/MarketingInfoPage";
import type { PublicPageData } from "@/features/home/marketingPages";
import { Newspaper } from "lucide-react";

export default function BlogPage() {
  const page: PublicPageData = {
    eyebrow: "Company",
    title: "Online Dating Tips & Relationship Advice",
    description: "Practical, safety-first guides for Indian singles creating authentic profiles, starting respectful conversations, spotting scams, and planning safer first dates.",
    icon: Newspaper,
    cta: { label: "Get Updates", href: "/register" },
    highlights: ["Practical advice for authentic profiles and conversations.", "Online dating safety guidance for Indian singles.", "Clear product, privacy, and subscription education."],
    metrics: [{ value: "4", label: "essential dating guides" }, { value: "18+", label: "adult community" }, { value: "Free", label: "public learning access" }],
    sections: [
      { title: "Create an authentic profile", body: "Use recent photos and specific details about your values, interests, lifestyle, and relationship goals.", points: ["Choose clear, current photos.", "Write a specific and honest bio.", "State your relationship intentions."] },
      { title: "Build respectful conversations", body: "Start from something in the other person's profile, ask open questions, and let trust develop without pressure.", points: ["Personalize the first message.", "Respect response time and boundaries.", "Never pressure someone to move off-platform."] },
      { title: "Date with safety in mind", body: "Verification is only one trust signal. Protect personal details, watch for scam patterns, and plan first meetings carefully.", points: ["Never send money or financial credentials.", "Meet in a public place.", "Tell a trusted person about your plan."] },
    ],
    longForm: [
      { title: "How to write a dating profile that feels genuine", paragraphs: ["A useful profile makes it easier for compatible people to start a real conversation. Replace vague claims such as “I like fun” with concrete details: the food you cook, the kind of weekends you enjoy, a hobby you are learning, and what a healthy relationship means to you.", "Use recent photographs that show your face clearly and represent your everyday life. Do not impersonate another person, hide material facts, or copy someone else's biography. A truthful profile attracts people who are interested in the real you."], points: ["Lead with two or three specific interests.", "Describe the relationship you hope to build.", "Use recent, unedited photos.", "Review spelling and remove sensitive contact details."] },
      { title: "How to start a respectful online conversation", paragraphs: ["Read the profile before sending a message. Mention a shared interest and ask one open question that is easy to answer. A thoughtful message is more useful than sending the same greeting to many people.", "Consent and comfort matter throughout the conversation. Respect a slow reply, a declined request, or a decision to stop chatting. Do not repeatedly message, sexualize a conversation without mutual interest, or pressure someone to share a phone number, photograph, or location."], points: ["Refer to something specific in the profile.", "Ask one genuine question at a time.", "Keep early communication on-platform.", "Accept rejection without argument."] },
      { title: "Recognize common romance-scam warning signs", paragraphs: ["Be cautious when a new contact quickly declares intense feelings, avoids live interaction, gives inconsistent personal details, or creates an urgent reason for money. Requests involving investment schemes, gift cards, travel emergencies, crypto transfers, or fees are serious warning signs.", "Never share an OTP, password, payment PIN, bank credential, identity document, or intimate image because someone pressures you. Save relevant evidence, stop the conversation, block the account, and use ConnectLove reporting or support tools."], points: ["Never send money to a match.", "Verify claims independently.", "Watch for urgency and secrecy.", "Block and report suspicious conduct."] },
      { title: "Plan a safer first meeting", paragraphs: ["Meet only when you feel comfortable. Choose a familiar public place during active hours, arrange your own transport, tell a trusted person where you are going, and keep your phone charged. A video conversation beforehand may provide useful context but does not guarantee identity or safety.", "Keep the first meeting short and avoid relying on the other person for transport, money, accommodation, food, or drinks. Leave at any time if you feel uncomfortable. In an immediate emergency, contact local emergency services."], points: ["Meet in a public place.", "Share the plan with someone you trust.", "Control your own transport.", "Leave if boundaries are not respected."] },
      { title: "Our editorial and safety standards", paragraphs: ["ConnectLove guidance is written for adults and aims to be accurate, respectful, inclusive, and clear about uncertainty. Product and policy details are reviewed against current site flows, while meaningful corrections are made when information changes.", "This content provides general education and cannot assess an individual situation or replace qualified medical, mental-health, legal, financial, or emergency help. Member stories or identifiable details require permission and privacy review."], points: ["Separate guidance from guarantees.", "Protect member privacy.", "Disclose material commercial relationships.", "Review dates and correct meaningful errors."] },
    ],
    actions: [{ title: "Read", body: "Visitor reads guidance." }, { title: "Apply", body: "User applies advice in profile or messages." }, { title: "Subscribe", body: "Footer newsletter POST connects to backend." }],
    faq: [{ question: "What should I include in an online dating profile?", answer: "Use recent photos and specific, truthful details about your interests, lifestyle, values, and relationship goals. Keep passwords, financial details, home address, and other sensitive information private." }, { question: "What are common online dating scam warning signs?", answer: "Warning signs include rapid declarations of love, inconsistent stories, avoiding live interaction, urgent requests for money, investment pitches, gift cards, crypto transfers, or pressure to keep the situation secret." }, { question: "How can I make a first date safer?", answer: "Meet in a public place, arrange your own transport, tell a trusted person your plan, keep your phone charged, limit alcohol, protect personal details, and leave if you feel uncomfortable." }, { question: "Is blog advice professional advice?", answer: "No. It provides general information and cannot replace qualified medical, legal, financial, mental-health, or emergency help." }],
    lastUpdated: "2026-07-23",
  };
  return <MarketingInfoPage page={page} />;
}
