"use client";

import { MarketingInfoPage } from "@/features/home/MarketingInfoPage";
import type { PublicPageData } from "@/features/home/marketingPages";
import { HelpCircle } from "lucide-react";

export default function HelpCenterPage() {
  const page: PublicPageData = {
    eyebrow: "Support",
    title: "Help Center",
    description: "Help for accounts, login, onboarding, discovery, messages, premium subscriptions, billing, reports, and privacy requests.",
    icon: HelpCircle,
    cta: { label: "Contact Support", href: "/contact-us" },
    highlights: ["Contact form is connected to backend support/contact.", "Tickets can be reviewed from support dashboards.", "Billing and safety issues route to the right team."],
    metrics: [{ value: "6", label: "help areas" }, { value: "24 hr", label: "reply target" }, { value: "Urgent", label: "safety path" }],
    sections: [
      { title: "Account help", body: "Users can get help with login, registration, onboarding, profile edits, photos, preferences, and account deletion.", points: ["Login issues.", "Profile updates.", "Delete account requests."] },
      { title: "Dating help", body: "Help content explains how likes, matches, discovery, messaging, reports, and blocks work.", points: ["Discovery questions.", "Message limits.", "Report/block flow."] },
      { title: "Getting support", body: "Use Contact Us when self-service guidance does not resolve the problem. Give the account email, issue category, relevant time, and a clear description without sharing passwords or payment PINs.", points: ["Choose a clear problem type.", "Attach only relevant screenshots.", "Keep your ticket details safe."] },
    ],
    longForm: [
      { title: "Registration, login, and account access", paragraphs: ["Check that the email is entered correctly and that the password meets current requirements. If login fails, avoid repeatedly guessing credentials or sharing OTPs. Use the supported recovery flow and confirm you are on the genuine ConnectLove site.", "New accounts must complete required onboarding and age eligibility steps before accessing the full member experience. Suspended, deactivated, or verification-pending accounts may have limited access."], points: ["Use the correct account email.", "Keep passwords and OTPs private.", "Complete required onboarding.", "Contact support for a locked or compromised account."] },
      { title: "Profiles, discovery, and matching", paragraphs: ["Profile information can be edited from the profile area, subject to any verification lock or safety restriction. Discovery results depend on available profiles, age and distance settings, Interested In, goals, interests, location, account eligibility, and prior actions.", "A like does not always create a match. Messaging generally requires mutual interest. If results are empty, broaden one filter at a time and confirm the profile, location permission, and account status are complete."], points: ["Update inaccurate profile details.", "Review filter combinations.", "Everyone removes the gender filter.", "Blocked or actioned profiles may not reappear."] },
      { title: "Messages, reports, and safety", paragraphs: ["If a conversation is unwanted, stop replying and use block or report where appropriate. Include relevant context when reporting, but do not provoke the person or continue an unsafe interaction merely to collect evidence.", "ConnectLove is not an emergency service. If someone is in immediate danger, contact local emergency services or law enforcement. Safety support can review platform accounts and activity but cannot provide emergency response."], points: ["Block unwanted contact.", "Report threats, scams, impersonation, or harassment.", "Do not send money or credentials.", "Use emergency services for urgent danger."] },
      { title: "Premium, payments, and refunds", paragraphs: ["Before paying, verify the plan, price, currency, billing period, and renewal terms shown during checkout. Keep the transaction reference. A pending or failed payment may delay activation even when a bank notification appears.", "For duplicate charges, missing activation, cancellation, or refund review, use Contact Us with Billing as the problem type. Never include a full card number, CVV, UPI PIN, OTP, or online banking password."], points: ["Premium is ₹199 per month.", "Elite is ₹399 per month.", "Refund eligibility depends on transaction facts and law.", "Safety features remain available without payment."] },
      { title: "Privacy, deletion, and response expectations", paragraphs: ["Many privacy and notification settings are self-service. For access, correction, deletion, consent, or grievance requests that are not available in Settings, use Privacy Request as the problem type and contact us from the account-linked email where possible.", "Response times vary with severity, verification needs, investigation complexity, payment provider coordination, and request volume. Automated acknowledgements do not mean a case has been fully reviewed. Avoid opening repeated tickets for the same issue because that can slow investigation."], points: ["Deactivation is different from deletion.", "Identity verification may be required.", "Keep the ticket reference.", "Reply in the same thread when possible."] },
    ],
    actions: [{ title: "Find topic", body: "User identifies account, safety, billing, or product issue." }, { title: "Contact support", body: "User submits backend-connected contact form." }, { title: "Resolve ticket", body: "Support reviews and updates status." }],
    roleAccess: [{ role: "Support", access: "Contacts, tickets, high priority queues, and trust-safety pages." }, { role: "Sales", access: "Plans, subscriptions, and revenue context." }, { role: "Admin", access: "Users, reports, tickets, verification, billing, and payments context." }],
    faq: [{ question: "How do I contact support?", answer: "Open Contact Us, choose a clear problem type, and provide the account email and relevant details." }, { question: "What should I never send?", answer: "Never send your password, OTP, CVV, UPI PIN, banking password, or unnecessary identity documents." }, { question: "Why has support asked me to verify my account?", answer: "Limited identity checks may be needed to prevent unauthorized access before changing or disclosing account information." }, { question: "What if the issue is urgent?", answer: "For immediate danger contact local emergency services. For serious platform safety concerns, report and block the account and then contact support." }],
  };
  return <MarketingInfoPage page={page} />;
}
